
# Uses from base rubber config
# domain: foo.com

# Uses from appserver (mongrel) rubber config 
# appserver_base_port: 8000
# appserver_count: 8

web_tools_port: 8080

ec2_security_groups:
  web:
    description: To open up port 80 for http server on web role
    rules:
      - ip_protocol: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
  web_tools:
    description: "To open up port #{web_tools_port} for internal/tools http server"
    rules:
      - ip_protocol: tcp
        from_port: "#{web_tools_port}"
        to_port: "#{web_tools_port}"
        cidr_ip: 0.0.0.0/0

roles:
  web:
    packages: [nginx]
    security_groups: [web]
  web_tools:
    packages: [nginx]
    security_groups: [web_tools]
