<%
  @path = "#{RUBBER_ROOT}/config/mongrel_cluster.yml"
%>
---
user: rails
group: rails
cwd: <%= RUBBER_ROOT %>
port: "<%= rubber_env.appserver_base_port %>"
environment: <%= RUBBER_ENV %>
address: <%= rubber_env.host %>
pid_file: tmp/pids/mongrel.pid
servers: <%= rubber_env.appserver_count %>
