
# REQUIRED: The credentials for creating/accessong your app's database
#
db_user: "#{app_name}"
db_pass:
db_name: "#{app_name}_#{RAILS_ENV}"

# REQUIRED: The command to use to do a full backup of your database using
#           "rake rubber:backup_db"
db_backup_cmd: "nice mysqldump -h %host% -u %user% --password=%pass% %name% | gzip -c > %backup_file%"

# REQUIRED: The directory to store the db data in
#
db_data_dir: /mnt/mysql_data

packages: [mysql-client, libmysql-ruby]

roles:
  mysql_master:
    db_server_id: 1
    packages: [mysql-server]
  mysql_slave:
    db_server_id: 2
    packages: [mysql-server]
    