# app_name: discourse
# domain: discourse.com
# ruby_version: 2.0.0-p247

roles:
  discourse:
    packages: [libtool, libpq-dev, gawk, pngcrush, imagemagick, python-software-properties, postgresql-contrib]