
# Uses from appserver (mongrel) rubber config 
# appserver_base_port: 8000
# appserver_count: 8

haproxy_monitor_port: 60001
haproxy_listen_port: 9000
haproxy_admin_port: 9100

roles:
  haproxy:
    packages: [libpcre3-dev]
