# Sets up memcached server and client as dalli

memcached_log_dir: /var/log/memcached
memcached_pid_file: /var/run/memcached.pid

gems: [dalli]

roles:
  memcached:
    packages: [memcached, libcache-memcached-perl]
